name: Deploy Model to a target

on:
  push:
    branches:
     - 'main'
    paths:
    - 'src/model/*'
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops'
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops'
        type: string
  workflow_run:
    workflows: [Create Execute Job through ml]
    types: [completed]

env:
  rg: '****'
  amlw: '****'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
    - name: Define rg and amlw
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "rg=${{ env.rg }}" >> "$GITHUB_ENV"
          echo "amlw=${{ env.amlw }}" >> "$GITHUB_ENV"
        else
          echo "rg=${{ github.event.inputs.resource_group }}" >> "$GITHUB_ENV"
          echo "amlw=${{ github.event.inputs.aml_workspace }}" >> "$GITHUB_ENV"
        fi

    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="${{ env.rg }}"
        az configure --defaults workspace="${{ env.amlw }}"

    - name: List models
      run: |
        az ml model list -w "${{ env.amlw }}" -g "${{ env.rg }}"

    - name: Deploy model
      run: |
        cd src
        az ml online-endpoint create --name diabetes-mlflow-mma --file create-endpoint.yml
        az ml online-deployment create --name mlflow-deployment --endpoint diabetes-mlflow-mma --file mlflow-deployment.yml --resource-group "${{ env.rg }}" --workspace-name "${{ env.amlw }}"